# App
app_name: "GoChat"
base_url: "http://example.com"

# API
swagger: true
rate_limit_time: 1
rate_limit_requests: 10
server_address: ":3100"

# Auth
auth_secret: "change_me_before_use_it_in_production"

# Cassandra
cluster: ["scylla"]
cluster_keyspace: "gochat"

# Redis
keydb: "keydb:6379"

# S3
s3_endpoint: minio:9000
s3_access_key_id: lF0b7V15OZCv2eGggCg5
s3_secret_access_key: 55ug80hPgx4nFPoFJXvwBHns1XwXmZrcKli8UHoz

# PostgreSQL
pg_dsn: "host=citus-master port=5432 user=postgres dbname=gochat sslmode=disable"

# OpenSearch
os_insecure_skip_verify: true
os_addresses: ["http://opensearch:9200"]
os_username: "admin"
os_password: "CustOM-Pa55w0Rd"

# NATS
nats_conn_string: "nats://nats:4222"
indexer_nats_conn_string: "nats://indexer-nats:4222"