{{- if .Values.indexer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gochat.fullname" . }}-indexer
  labels:
    {{- include "gochat.componentLabels" (dict "Context" . "Component" "indexer") | nindent 4 }}
spec:
  replicas: {{ .Values.indexer.replicaCount }}
  selector:
    matchLabels:
      {{- include "gochat.componentSelectorLabels" (dict "Context" . "Component" "indexer") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gochat.componentSelectorLabels" (dict "Context" . "Component" "indexer") | nindent 8 }}
    spec:
      containers:
        - name: indexer
          image: "{{ .Values.indexer.image.repository }}:{{ .Values.indexer.image.tag }}"
          imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
{{- if .Values.indexer.env }}
          env:
{{ toYaml .Values.indexer.env | indent 12 }}
{{- end }}
          volumeMounts:
            - name: config
              mountPath: /dist/config.yaml
              subPath: config.yaml
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "gochat.fullname" . }}-indexer-config
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
