{{- if .Values.ingress.enabled }}
{{- $root := . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gochat.fullname" . }}
  labels:
    {{- include "gochat.labels" . | nindent 4 }}
{{- $annotations := dict -}}
{{- if .Values.ingress.annotations -}}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{- $_ := set $annotations $key $value }}
  {{- end }}
{{- end }}
{{- if .Values.traefik.enabled }}
  {{- $middlewareName := printf "%s-%s" .Release.Namespace (printf "%s-ui-stripprefix" (include "gochat.fullname" .)) }}
  {{- if not (hasKey $annotations "traefik.ingress.kubernetes.io/router.middlewares") }}
    {{- $_ := set $annotations "traefik.ingress.kubernetes.io/router.middlewares" (printf "%s@kubernetescrd" $middlewareName) }}
  {{- end }}
{{- end }}
{{- if gt (len $annotations) 0 }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
{{- range .paths }}
{{- if or (ne .service "landing") $root.Values.landing.enabled }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ printf "%s-%s" (include "gochat.fullname" $root) .service }}
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end }}
{{- end }}
