{{- if .Values.migrations.enabled }}
{{- $defaultPg := "" -}}
{{- if .Values.citus.enabled -}}
  {{- $defaultPg = printf "postgres://%s:%s@%s-citus-master:%v/%s?sslmode=disable" .Values.citus.auth.postgresUser .Values.citus.auth.postgresPassword (include "gochat.fullname" .) (int .Values.citus.master.service.port) .Values.citus.auth.postgresDb -}}
{{- end -}}
{{- $defaultCassandra := "" -}}
{{- if .Values.scylla.enabled -}}
  {{- $defaultCassandra = printf "cassandra://%s-scylla:%v/%s?x-multi-statement=true" (include "gochat.fullname" .) (int .Values.scylla.service.ports.cql) .Values.scylla.lifecycle.createKeyspace.keyspace -}}
{{- end -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gochat.fullname" . }}-migrations
  labels:
    {{- include "gochat.componentLabels" (dict "Context" . "Component" "migrations") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit | default 5 }}
  template:
    metadata:
      labels:
        {{- include "gochat.componentSelectorLabels" (dict "Context" . "Component" "migrations") | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: postgres-migrations
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          args:
            - -path=/migrations/postgres
            - -database={{ default $defaultPg .Values.migrations.pgAddress }}
            - up
          volumeMounts:
            - name: postgres-migrations
              mountPath: /migrations/postgres
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
      containers:
        - name: cassandra-migrations
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          args:
            - -path=/migrations/cassandra
            - -database={{ default $defaultCassandra .Values.migrations.cassandraAddress }}
            - up
          volumeMounts:
            - name: cassandra-migrations
              mountPath: /migrations/cassandra
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
      volumes:
        - name: postgres-migrations
          configMap:
            name: {{ include "gochat.fullname" . }}-postgres-migrations
        - name: cassandra-migrations
          configMap:
            name: {{ include "gochat.fullname" . }}-cassandra-migrations
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
