apiVersion: v2
name: gochat
description: A Helm chart for deploying the GoChat application stack
icon: https://avatars.githubusercontent.com/u/15716596?s=200&v=4
type: application
version: 0.1.0
appVersion: "0.1.0"
