global:
  scrape_interval: 15s
  evaluation_interval: 30s
  body_size_limit: 15MB
  sample_limit: 1500
  target_limit: 30
  label_limit: 30
  label_name_length_limit: 200
  label_value_length_limit: 200
  query_log_file: query.log
  scrape_failure_log_file: fail.log
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab
    foo: bar

runtime:
  gogc: 42

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: gochat-api
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3100

  - job_name: gochat-attachments
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - attachments:3200

  - job_name: gochat-ws
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - ws:3100

  - job_name: gochat-sfu
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    http_sd_configs:
      - url: http://webhook:3200/api/v1/webhook/sfu/prom_sd
        refresh_interval: 5s
        authorization:
          type: Bearer
          credentials: "REPLACE_ME_WITH_PROM_TOKEN"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [region]
        target_label: region
      - source_labels: [sfu_id]
        target_label: sfu_id

  - job_name: gochat-auth
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth:3100

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: postgres-citus-master
    static_configs:
      - targets:
          - postgres-exporter-master:9187

  - job_name: postgres-citus-worker
    static_configs:
      - targets:
          - postgres-exporter-worker:9187

storage:
  tsdb:
    out_of_order_time_window: 30m
