# Auth
auth_secret: "change_me_before_use_it_in_production"

# Cassandra
cluster: ["scylla"]
cluster_keyspace: "gochat"

# YugabyteDB YSQL
pg_dsn: "host=yugabyte port=5433 user=yugabyte password=yugabyte dbname=gochat sslmode=disable"

# Cache Address (KeyDB)
cache_addr: "keydb:6379"
