# Auth
auth_secret: "change_me_before_use_it_in_production"

# Cassandra
cluster: ["scylla"]
cluster_keyspace: "gochat"

# PostgreSQL
pg_dsn: "host=citus-master port=5432 user=postgres dbname=gochat sslmode=disable"
